{% set name = 'vampyr' %}
{% set version = '0.2rc0' %}
{% set sha256 = '587904da160c22258d9f1d7c386711676924cc2a916727606c7346a56e49b608' %}
{% set pyver = PY_VER.replace(".", "") %}
{% set build = 3 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MRChemSoft/vampyr/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]
  binary_relocation: true
  run_exports:
    - {{ pin_subpackage('vampyr', max_pin='x.x') }}

requirements:
  build:
    - cmake >=3.17
    - {{ compiler('cxx') }}
    - pybind11 =*=*py{{ pyver }}*
    - ninja
  host:
    - mrcpp
    - python

test:
  requires:
    - numpy
    - pytest
  imports:
    - vampyr
  commands:
    # Verify existence and execution
    - ls -l $SP_DIR/vampyr
    - test -f $SP_DIR/vampyr/_vampyr*.so
    # Inspect linkage
    - ldd -v $SP_DIR/vampyr/_vampyr*.so                                   # [linux]
    - otool -L $SP_DIR/vampyr/_vampyr*.so                                 # [osx]

outputs:
  - name: vampyr
    files:
      - {{ SP_DIR }}/vampyr

about:
  home: https://github.com/MRChemSoft/vampyr
  dev_url: https://github.com/MRChemSoft/vampyr
  license: LGPL-3.0-or-later
  license_url: https://opensource.org/licenses/LGPL-3.0
  license_file: LICENSE
  license_family: LGPL
  summary: Very Accurate Multiresolution Python Routines

extra:
  recipe-maintainers:
    - robertodr
    - bjorgve
    - stigrj
